### ISSUE TITLE
不止一个页面，存在路由，项目应该怎么修改

### ISSUE THREAD

**Issue by revanli** [page-pipepline/pipeline-template-react#1]
@CntChen  感谢开源如此好的项目

在实际开发中，存在不止一个页面，多个页面的话，server/node.js应该怎么修改才能实时预览不同的页面？

**Comment by CntChen** [comment]
好问题.
页面路由是个很难搞的问题. 特别是前端路由. 

## 前端路由
因为搭建工具的一个前提假设是**页面只有一份组件列表**, 而路由是每个路由里面有一个组件列表. 这样的话前端路由的组件结构和搭建工具的组件结构是冲突的.
```js
// 搭建工具
[
  componentA,
  componentB,
  ...
]
```

```js
// 前端路由
[
  routeA: [
    componentA,
    componentB,
    ...
  ],
  routeB: [
    ...
  ],
]
```

而且pipeline是和前端框架解耦的, 我比较怀疑不同前端框架的路由差异会使得编辑器设计变得很复杂.

## 页面路由
简单的处理思路是没有前端路由, 只有页面路由: 路由的跳转都是跳新的页面.

比如阿里的云凤蝶:
![image](https://user-images.githubusercontent.com/4598445/68219102-657f0c80-0020-11ea-8422-736744c68f5d.png)

可以看到这个'页面'的路由其实是多个独立页面, 只是把他们放在一个编辑器里面编辑. 
这其实可以做的, 就是编辑器支持不同页面的编辑切换, 在数据库层面上关联多个页面.

也可以从业务角度考虑: 是否真需要路由？

**Comment by revanli** [comment]
@CntChen 感谢详细的回复:thumbsup:，我非常赞同你的观点。

在实际的业务中，确实有碰到前端路由的问题，如果要把前端路由考虑进去的话，可能模板就要做成同构的模式，极大的增加了开发的难度和维护成本。

带着问题去看模板源码的时候也有冒出来这个想法，就是不考虑前端路由，一个页面一份组件列表，多个组件组成一个页面，多个页面组成一个模板，这样就可以自由的组合成新的模板，从开发和维护的角度来说都是很方便的。现在坚定了这个想法。
